#!/usr/bin/env bash
# Bash Script that transfers a file from a client to a server.

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH TO_SSH_KEY"
	exit
fi
scp -i $4 $1 $3@$2:~/
