#!/usr/bin/env bash
# Bash script that installs nginx on a server.
apt update
apt-get -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!"> /var/www/html/index.html
sed -i 's/server_name _;/server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 http:\/\/wikipedia.com\;\n}/' /etc/nginx/sites-available/default
service nginx restart
