#!/usr/bin/env bash
# Bash script that installs nginx on a server.
apt-get -y nginx
ufw allow 'Nginx HTTP'
echo "events{} http{server{listen 80; return 200 \"Hello World!\n\"; location /redirect_me {return 301 \"https://www.youtube.com/watch?v=QH2-TGUlwu4\";}}}" > /etc/nginx/nginx.conf
service nginx restart
