#!/usr/bin/env bash
# Bash script that installs nginx on a server.
apt update
apt-get -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!"> /var/www/html/index.html
sed -i 's/server_name _;/server_name _;\n\n\t error_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\t root \/usr\/share\/nginx\/html;\n\t\t internal;\n}/' /etc/nginx/sites-available/default
service nginx restart
