#!/usr/bin/env bash
# Configure the server to enable Nginx on port 80
sed -i 's/listen [0-9]*;/listen 80;/' /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
