#!/usr/bin/env bash
# Displays a list of currently running processes.
#
# Must show all processes, for all users, including those which might not have TTY
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest | tail -n +2
