#!/usr/bin/env bash
#Displays numbers from 1 to 100 in FizzBuzz format

for i in {1..100}
do
fizz=$((i % 3))
buzz=$((i % 5))
if [ $fizz -eq 0 ] && [ $buzz -eq 0 ]
then
echo "FizzBuzz"
elif [ $fizz -eq 0 ]
then
echo "Fizz"
elif [ $buzz -eq 0 ]
then
echo "Buzz"
else
echo "$i"
fi
done
