#!/usr/bin/env bash
#This script prints out "Best School" 10 times
count=1
while [ $count -le 10 ]
do
if [ $count -eq 10 ]
then
echo -n "Best School"
else
echo "Best School"
fi
count=$((count+1))
done
