#!/usr/bin/env bash
#Print Best School but for the 9th iteration print Best school and Hi
count=1
while [ $count -le 10 ]
do
echo "Best School"
if [ $count -eq 9 ]
then
echo "Hi"
fi
count=$((count+1))
done
