#!/usr/bin/env bash
#Loop from 1-10 printing text based on a condition
count=1
while [ $count -le 10 ]
do
if [ $count -eq 4 ]
then
echo "bad luck"
elif [ $count -eq 8 ]
then
echo "good luck"
else
echo "Best School"
fi
count=$((count+1))
done
