#!/usr/bin/env bash
#This bash script gives you information about the school file

filename="school"
if [ -e "$school" ]
then
    echo "school file exists"
    if [ -s "$filename" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -e "$filename" ]
    then
        echo "school file is a regular file"
    fi
else
    echo "school file does not exist"
fi