#!/usr/bin/env bash
#Change localhost to resolve to different IP
cp /etc/hosts ~/hosts.new
sed -i -e '$a 127.0.0.2 localhost' ~/hosts.new
sed -i -e '$a 8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
