#!/usr/bin/env bash
# This script configures the Nginx container to run as the 'nginx' user and listen on port 8080
useradd -r -s /sbin/nologin nginx
chown -R nginx:nginx /var/lib/nginx /var/log/nginx /etc/nginx
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-available/default.conf
sudo -u nginx nginx -g 'daemon off'